# Generated by Django 5.0.6 on 2025-08-12 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('country_of_residency', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50)),
                ('number_of_days', models.PositiveIntegerField()),
                ('number_of_people', models.PositiveIntegerField()),
                ('travel_date', models.DateField()),
                ('accommodation', models.CharField(choices=[('budget', 'Budget'), ('mid', 'Mid range'), ('luxury', 'Luxury')], max_length=10)),
                ('budget', models.CharField(choices=[('0-1000', '0-$1000'), ('1000-2000', '1k - 2k'), ('2000-3000', '2k - 3k'), ('4000+', '4k+'), ('any', 'Budget doesn’t matter')], max_length=20)),
                ('preferred_activities', models.TextField(blank=True)),
                ('special_request', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinations.destination')),
            ],
        ),
    ]
